document.getElementById("myHead").innerHTML =
    " <meta charset='utf-8'>"
    + "<meta http-equiv='X-UA-Compatible' content='IE=edge'>"
    + "<meta name='viewport' content='width=device-width, initial-scale=1'>"
    + "<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->"
    + "<meta name='description' content=''>"
    + "<meta name='author' content=''>"
    + "<link rel='icon' href='images/wcf_icon.ico'>"
    + "<title>Wantage Christian Fellowship</title>"
    + "<link href='https://fonts.googleapis.com/css?family=Fira Sans' rel='stylesheet'>"
    + "<link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>"
    + "<link href='https://fonts.googleapis.com/css?family=Droid Serif' rel='stylesheet'>"
    + "<!-- Bootstrap core CSS -->"
    + "<link href='css/bootstrap.css' rel='stylesheet'>"
    + "<!-- Custom styles for this template -->"
    + "<link href='css/event_cards.css' rel='stylesheet'>"
    + "<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->"
    + "<link href='css/ie10-viewport-bug-workaround.css' rel='stylesheet'>"
    + "<!-- Custom styles for this template -->"
    + "<link href='css/starter-template.css' rel='stylesheet'>"
    + "<!-- My css settings -->"
    + "<link href='css/wcf.css' rel='stylesheet'>";


document.getElementById("myNav").innerHTML =
    "<div class='span12 row-fluid' style='padding:0 5%'>"
    + "   <nav class='navbar navbar-default navbar-fixed-top container-fullwidth' role='navigation' style='padding:0 5%'>"
    + "    <div class='container-fluid'>"
    + "     <div class='navbar-header'>"
    + "      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar' aria-expanded='false' aria-controls='navbar'>"
    + "        <span class='sr-only'>Toggle navigation</span>"
    + "        <span class='icon-bar'></span>"
    + "        <span class='icon-bar'></span>"
    + "        <span class='icon-bar'></span>"
    + "      </button>"
    + "      <a href='http://www.wantagechristianfellowship.org.uk'>"
    + "        <img src='images/wcf_tab_on_transparent.png' width='98px' height='54px' class='d-inline-block align-top' alt='WCF' id='wcf_logo'>"
    + "      </a>"
    + "    </div>"
    + "    <div id='navbar' class='collapse navbar-collapse'>"
    + "      <ul class='nav navbar-nav'>"
    + "        <li><a href='./whoweare.html'>Who we are</a></li><!-- statement of faith and strap line -->"
    + "        <li class='dropdown'><a href='./groups.html'>Groups<span class='caret'></span></a>"
    + "          <ul class='dropdown-menu'>"
    + "            <li><a href='./kids_work.html'>Kids work</a></li>"
    + "            <li><a href='./worship.html'>Worship</a></li>"
    + "            <li><a href='./balsam.html'>Balsam</a></li>"
    + "            <li><a href='./lifted.html'>Lifted</a></li>"
    + "            <li><a href='./streetpastors.html'>Street Pastors</a></li>"
    + "            <li><a href='./welcome.html'>Welcoming</a></li>"
    + "            <li><a href='./pastoral.html'>Pastoral Team</a></li>"
    + "          </ul>"
    + "        </li>"
    + "        <li><a href='./events.html'>What\'s on</a></li><!-- calendar of upcoming events -->"
    + "        <li><a href='./leadership.html'>Leadership</a></li><!-- pics and desc of elders -->"
    + "        <li><a href='./contact.html'>Contact</a></li>"
    + "      </ul>"
    + "    </div><!--/.nav-collapse -->"
    + "  </div>"
    + "</nav>"

document.getElementById("myFooter").innerHTML =
    "<footer class='footer'>"
    + "     <div class='container'>"
   + "        <p class='text-muted'>&#9400 2017. All rights reserved.</p>"
   + "      </div>"
   + "    </footer>"
   + ""
    + "</div>";



